# -*- coding: utf-8 -*-
"""Sales Data Analysis Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W2GXlwXjbKCXq1fCNiq_rDGCMzuUw0jL
"""

import pandas as pd
import matplotlib.pyplot as plt

# =========================
# LOAD EXCEL DATA
# =========================
df = pd.read_excel("/content/Sales-Data-Analysis-Workbook.xlsx")

# =========================
# CLEAN COLUMN NAMES
# =========================
df.columns = df.columns.str.strip().str.replace(" ", "_").str.replace("\n", "_")

# =========================
# DATA TYPE CLEANING
# =========================
df["Date"] = pd.to_datetime(df["Date"], errors="coerce")

money_cols = ["Ticket_Price_Price_Per_Unit","Sales_Price_Per_Unit","Cost_per_Unit","Discount_Amount","Total_Profit"]
for col in money_cols:
    df[col] = df[col].astype(str).str.replace("$","").str.replace(",","").str.strip()

df["Discount_Given"] = df["Discount_Given"].astype(str).str.replace("%","")

for col in money_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

df["Discount_Given"] = pd.to_numeric(df["Discount_Given"], errors="coerce")
df["Quantity"] = pd.to_numeric(df["Quantity"], errors="coerce")

# =========================
# KPI CREATION
# =========================
df["Revenue"] = df["Sales_Price_Per_Unit"] * df["Quantity"]
df["Cost_Total"] = df["Cost_per_Unit"] * df["Quantity"]
df["Profit_Calc"] = df["Revenue"] - df["Cost_Total"]
df["Profit_Margin_%"] = (df["Profit_Calc"] / df["Revenue"]) * 100
df["Month"] = df["Date"].dt.to_period("M")

# =========================
# BASIC RESULTS
# =========================
print("\nTOTAL REVENUE:", df["Revenue"].sum())
print("\nTOTAL PROFIT:", df["Profit_Calc"].sum())

# =========================
# ITEM ANALYSIS
# =========================
print("\nTOP ITEMS BY PROFIT")
print(df.groupby("Item_Code")["Profit_Calc"].sum().sort_values(ascending=False).head(10))

print("\nWORST ITEMS")
print(df.groupby("Item_Code")["Profit_Calc"].sum().sort_values().head(10))

# =========================
# SALESPERSON PERFORMANCE
# =========================
salesperson_perf = df.groupby("Sales_Person").agg({
    "Revenue":"sum",
    "Profit_Calc":"sum",
    "Quantity":"sum"
}).sort_values(by="Profit_Calc", ascending=False)

print("\nSALESPERSON PERFORMANCE")
print(salesperson_perf)

# =========================
# MANAGER PERFORMANCE
# =========================
print("\nMANAGER PERFORMANCE")
print(df.groupby("Manager_On_Duty")[["Revenue","Profit_Calc"]].sum())

# =========================
# DISCOUNT IMPACT
# =========================
print("\nDISCOUNT IMPACT")
print(df.groupby("Discount_Given")[["Revenue","Profit_Calc"]].mean())

# =========================
# POSTAL CODE ANALYSIS
# =========================
print("\nHIGH VALUE AREAS")
print(df.groupby("Postal_Code")[["Revenue","Profit_Calc"]].sum().sort_values(by="Revenue", ascending=False))

# =========================
# MONTHLY TREND
# =========================
monthly_sales = df.groupby("Month")["Revenue"].sum()
print("\nMONTHLY SALES TREND")
print(monthly_sales)

# =========================
# PEAK SALES DAY
# =========================
print("\nTOP SALES DAYS")
print(df.groupby("Date")["Revenue"].sum().sort_values(ascending=False).head())

# =========================
# CORRELATION
# =========================
print("\nCORRELATION MATRIX")
print(df[["Revenue","Profit_Calc","Quantity","Discount_Given"]].corr())

# =========================
# VISUALIZATIONS
# =========================
df.groupby("Sales_Person")["Revenue"].sum().plot(kind="bar", title="Sales by Salesperson")
plt.show()

df.groupby("Date")["Profit_Calc"].sum().plot(title="Profit Trend")
plt.show()

monthly_sales.plot(title="Monthly Revenue Trend")
plt.show()

df.plot.scatter(x="Quantity", y="Profit_Calc", title="Quantity vs Profit")
plt.show()